In [1]:
import pandas as pd
import numpy as np

from pneumococcus_data import data_observation

In [2]:
Iran, Denmark, Brazil, Nepal, Mozambique = data_observation()

In [4]:
#export Iran
country = np.array([Iran, Nepal, Brazil, Denmark, Mozambique], dtype = object)
name = ['Iran', 'Nepal', 'Brazil', 'Denmark', 'Mozambique']

for i in range (0, 5):
    print(name[i])
    print(repr(np.array(country[i].strain)))
    print(repr(np.array(country[i].cases)))
    print('-----------------------------------------------------------------------------------------------------------------')

Iran
array(['19', '6', '14', '19F', '17', '21', '20', '12F', '11', '3', '4',
       '22', '6A', '1', '23', '6B', '16', '5', '19A', '22A', '15B', '18C',
       '9V', '10', '23C', '9', '18', '23B', '15', '4B'], dtype=object)
array([0.08278581, 0.07621551, 0.07227332, 0.07227332, 0.06438896,
       0.05387648, 0.05124836, 0.04862024, 0.04467806, 0.04336399,
       0.03285151, 0.02890933, 0.02890933, 0.02628121, 0.02496715,
       0.02365309, 0.02365309, 0.02233903, 0.02233903, 0.02233903,
       0.02233903, 0.02233903, 0.01839685, 0.01708279, 0.01708279,
       0.0131406 , 0.01051248, 0.01051248, 0.00131406, 0.00131406])
-----------------------------------------------------------------------------------------------------------------
Nepal
array(['NT4b', '14', '6A', '19F', 'NT2', '23F', '15B', '3', '6B', '10A',
       'NT4a', '35A', '11D', '34', '17F', '35B', '35F', '9V', '13', '23A',
       '6C', '19A', '33B', '35C', '16F', '7C', '39', '4', '20', '45', '8',
       '22F', '21', '15C', '15A', '9N', '7B', '23B', '29', '19B', '18C',
       '24A', '6D', '38', '9L', '28F', '22A', '10F', '31', '33C', '48',
       'NT3b', '19C', '33F', '33A', '32F', '28A', '25F', '24B', '18A',
       '17A', '12F', '11B', '11A', '40', '37', '36', '5', 'NT'],
      dtype=object)
array([0.07142857, 0.05760369, 0.05299539, 0.05299539, 0.05069124,
       0.04608295, 0.0437788 , 0.03225806, 0.03225806, 0.02764977,
       0.02534562, 0.02534562, 0.02304147, 0.02073733, 0.02073733,
       0.02073733, 0.02073733, 0.02073733, 0.01843318, 0.01612903,
       0.01612903, 0.01612903, 0.01612903, 0.01612903, 0.01382488,
       0.01382488, 0.01382488, 0.01152074, 0.01152074, 0.01152074,
       0.00921659, 0.00921659, 0.00921659, 0.00921659, 0.00921659,
       0.00921659, 0.00921659, 0.00691244, 0.00691244, 0.00691244,
       0.00460829, 0.00460829, 0.00460829, 0.00460829, 0.00460829,
       0.00460829, 0.00460829, 0.00460829, 0.00460829, 0.00460829,
       0.00460829, 0.00460829, 0.00230415, 0.00230415, 0.00230415,
       0.00230415, 0.00230415, 0.00230415, 0.00230415, 0.00230415,
       0.00230415, 0.00230415, 0.00230415, 0.00230415, 0.00230415,
       0.00230415, 0.00230415, 0.00230415, 0.00230415])
-----------------------------------------------------------------------------------------------------------------
Brazil
array(['6B', '19F', '14', '6A', '15C', '23F', '16F', '17F', '6', '19A',
       '11A', '23B', '6C', '4', '18', '23A', '3', '10A', '15A', '34',
       '39', '1', '9N', '12F', '29', '35B'], dtype=object)
array([0.13768116, 0.12318841, 0.0942029 , 0.08695652, 0.07246377,
       0.05797101, 0.04347826, 0.04347826, 0.03623188, 0.03623188,
       0.02898551, 0.02898551, 0.02898551, 0.02898551, 0.02173913,
       0.02173913, 0.01449275, 0.01449275, 0.01449275, 0.01449275,
       0.01449275, 0.00724638, 0.00724638, 0.00724638, 0.00724638,
       0.00724638])
-----------------------------------------------------------------------------------------------------------------
Denmark
array(['6A', 'NC', '14', '11A', '19F', '23F', '18C', '19A', '15B', '22F',
       '16F', '6B', '4', '3', '35F', '15C', '9V', '24F', '7F', '21', '38',
       '8', '7B', '37', '18F', '18B', '10A', '15A', '17F', '20', '24A',
       '35B', '9N'], dtype=object)
array([0.15613383, 0.08178439, 0.07806691, 0.07806691, 0.06319703,
       0.05576208, 0.05204461, 0.04460967, 0.04460967, 0.04460967,
       0.04089219, 0.04089219, 0.0260223 , 0.02230483, 0.01858736,
       0.01858736, 0.01858736, 0.01486989, 0.01115242, 0.01115242,
       0.01115242, 0.00743494, 0.00743494, 0.00743494, 0.00743494,
       0.00743494, 0.00743494, 0.00371747, 0.00371747, 0.00371747,
       0.00371747, 0.00371747, 0.00371747])
-----------------------------------------------------------------------------------------------------------------
Mozambique
array(['19A', '13', '6A', '23F', '7C', '19F', 'NT', '15B', '11A', '35B',
       '15C', '15A', '34', '10A', '23B', '21', '14', '6B', '16F', '28F',
       '3', '9V', '23A', '31', '38', '6C', '8', '18C', '4', '19B', '9N',
       '20', '9A', '18A', '33F', '33C', '17F', '35A', '35F', '18',
       '6A/6B', '24F', '5', '46', '12F/12A/4'], dtype=object)
array([0.08202654, 0.0747889 , 0.06996381, 0.06031363, 0.05548854,
       0.05428227, 0.05186972, 0.04945718, 0.0482509 , 0.0482509 ,
       0.039807  , 0.03618818, 0.03136309, 0.03015682, 0.02895054,
       0.026538  , 0.02412545, 0.02412545, 0.02412545, 0.02291918,
       0.02050663, 0.01206273, 0.01206273, 0.00723764, 0.00603136,
       0.00603136, 0.00603136, 0.00482509, 0.00482509, 0.00482509,
       0.00482509, 0.00482509, 0.00241255, 0.00241255, 0.00241255,
       0.00241255, 0.00241255, 0.00241255, 0.00120627, 0.00120627,
       0.00120627, 0.00120627, 0.00120627, 0.00120627, 0.00120627])
-----------------------------------------------------------------------------------------------------------------